import { config, fields, collection, singleton } from '@keystatic/core';

const programImages = {
  directory: 'public/site/programs',
  publicPath: '/site/programs/',
} as const;

const blogImages = {
  directory: 'public/site/blog',
  publicPath: '/site/blog/',
} as const;

const branding = {
  directory: 'public/site/branding',
  publicPath: '/site/branding/',
} as const;

export default config({
  storage: { kind: 'local' },
  singletons: {
    site: singleton({
      label: 'Website content',
      path: 'content/site/',
      format: { data: 'json' },
      schema: {
        siteName: fields.text({ label: 'Site / org name' }),
        logo: fields.image({
          label: 'Logo (optional — text shows if empty)',
          ...branding,
        }),
        logoAlt: fields.text({
          label: 'Logo alt text',
          description: 'Usually the organization name',
          validation: { isRequired: false },
        }),
        heroHeadline: fields.text({ label: 'Hero headline' }),
        heroSub: fields.text({ label: 'Hero subhead', multiline: true }),
        heroImage: fields.image({
          label: 'Hero image',
          directory: 'public/site/hero',
          publicPath: '/site/hero/',
        }),
        heroImageAlt: fields.text({
          label: 'Hero image alt text',
          validation: { isRequired: false },
        }),
        heroCtaPrimaryLabel: fields.text({ label: 'Primary hero button' }),
        heroCtaPrimaryHref: fields.text({ label: 'Primary hero link' }),
        heroCtaSecondaryLabel: fields.text({ label: 'Secondary hero button' }),
        heroCtaSecondaryHref: fields.text({ label: 'Secondary hero link' }),
        youthTagline: fields.text({ label: '“By the youth” section title' }),
        youthBody: fields.text({ label: '“By the youth” body', multiline: true }),
        transformTitle: fields.text({ label: 'Transform section title' }),
        transformBody: fields.text({ label: 'Transform section body', multiline: true }),
        transformCtaLabel: fields.text({ label: 'Transform CTA label' }),
        transformCtaHref: fields.text({ label: 'Transform CTA link' }),
        inclusivityTitle: fields.text({ label: 'Inclusivity block title' }),
        inclusivityBody: fields.text({ label: 'Inclusivity block body', multiline: true }),
        pillarsIntroTitle: fields.text({ label: 'Pillars intro title' }),
        pillarsIntroBody: fields.text({ label: 'Pillars intro body', multiline: true }),
        statStudents: fields.integer({ label: 'Stat: students trained' }),
        statVolunteers: fields.integer({ label: 'Stat: volunteers' }),
        statCampaigns: fields.integer({ label: 'Stat: campaigns' }),
        statEmployment: fields.integer({ label: 'Stat: placements / jobs' }),
        csrTitle: fields.text({ label: 'CSR section title' }),
        csrLead: fields.text({ label: 'CSR lead paragraph', multiline: true }),
        csrPoint1Title: fields.text({ label: 'CSR point 1 title' }),
        csrPoint1Body: fields.text({ label: 'CSR point 1 body', multiline: true }),
        csrPoint2Title: fields.text({ label: 'CSR point 2 title' }),
        csrPoint2Body: fields.text({ label: 'CSR point 2 body', multiline: true }),
        csrPoint3Title: fields.text({ label: 'CSR point 3 title' }),
        csrPoint3Body: fields.text({ label: 'CSR point 3 body', multiline: true }),
        partnerTitle: fields.text({ label: 'Partner CTA title' }),
        partnerBody: fields.text({ label: 'Partner CTA body', multiline: true }),
        phone: fields.text({ label: 'Phone (display)' }),
        email: fields.text({ label: 'Email' }),
        address: fields.text({ label: 'Address', multiline: true }),
        socialFacebook: fields.text({ label: 'Facebook URL (https://...)' }),
        socialTwitter: fields.text({ label: 'X / Twitter URL' }),
        socialInstagram: fields.text({ label: 'Instagram URL' }),
        socialLinkedin: fields.text({ label: 'LinkedIn URL' }),
        socialYoutube: fields.text({ label: 'YouTube URL' }),
        donateUrl: fields.text({ label: 'Donate button URL' }),
        aboutMissionTitle: fields.text({ label: 'About: mission title' }),
        aboutMissionBody: fields.text({ label: 'About: mission', multiline: true }),
        aboutStoryTitle: fields.text({ label: 'About: story title' }),
        aboutStoryBody: fields.text({ label: 'About: story', multiline: true }),
        aboutValuesTitle: fields.text({ label: 'About: values title' }),
        aboutValuesBody: fields.text({ label: 'About: values', multiline: true }),
        contactIntro: fields.text({ label: 'Contact page intro', multiline: true }),
        donateIntro: fields.text({ label: 'Donate page intro', multiline: true }),

        headerNav: fields.array(
          fields.object({
            label: fields.text({ label: 'Menu label' }),
            href: fields.text({ label: 'Menu link (e.g. /about)' }),
          }),
          { label: 'Header menu items' }
        ),
        headerPartnerLabel: fields.text({ label: 'Header partner button label' }),
        headerVolunteerLabel: fields.text({ label: 'Header volunteer button label' }),
        volunteerPageHref: fields.text({ label: 'Volunteer button link (e.g. /contact)' }),
        headerDonateLabel: fields.text({ label: 'Header donate button label' }),

        footerTagline: fields.text({ label: 'Footer tagline', multiline: true }),
        footerExploreHeading: fields.text({ label: 'Footer explore heading' }),
        footerContactHeading: fields.text({ label: 'Footer contact heading' }),
        footerFollowHeading: fields.text({ label: 'Footer follow heading' }),
        footerMediaText: fields.text({ label: 'Footer media / due diligence text', multiline: true }),
        footerDonateLabel: fields.text({ label: 'Footer donate button label' }),
        footerVolunteerLabel: fields.text({ label: 'Footer volunteer button label' }),
        footerCsrLabel: fields.text({ label: 'Footer CSR button label' }),
        footerLegalLine: fields.text({ label: 'Footer legal line' }),
        footerSublegalLine: fields.text({ label: 'Footer sub-legal line' }),
        footerExploreLinks: fields.array(
          fields.object({
            label: fields.text({ label: 'Link label' }),
            href: fields.text({ label: 'Link href' }),
          }),
          { label: 'Footer explore links' }
        ),

        programsPageEyebrow: fields.text({ label: 'Programs page eyebrow' }),
        programsPageTitle: fields.text({ label: 'Programs page title' }),
        programsPageIntro: fields.text({ label: 'Programs page intro', multiline: true }),
        programsCardCtaText: fields.text({ label: 'Programs card CTA text' }),
        programsNoImageText: fields.text({ label: 'Programs missing image text' }),
        programDetailBackLabel: fields.text({ label: 'Program detail back label' }),
        programDetailGalleryTitle: fields.text({ label: 'Program detail gallery title' }),
        programDetailGalleryIntro: fields.text({ label: 'Program detail gallery intro' }),

        blogPageEyebrow: fields.text({ label: 'Blog page eyebrow' }),
        blogPageTitle: fields.text({ label: 'Blog page title' }),
        blogPageIntro: fields.text({ label: 'Blog page intro', multiline: true }),
        blogCardPlaceholderText: fields.text({ label: 'Blog card placeholder text' }),
        blogDetailBackLabel: fields.text({ label: 'Blog detail back label' }),

        donatePageEyebrow: fields.text({ label: 'Donate page eyebrow' }),
        donatePageTitle: fields.text({ label: 'Donate page title' }),
        donateOnlineLabel: fields.text({ label: 'Donate online button label' }),
        donateDirectLabel: fields.text({ label: 'Donate button label (internal link)' }),
        donateDiscussLabel: fields.text({ label: 'Discuss grant button label' }),
        donateHelperText: fields.text({ label: 'Donate helper text', multiline: true }),

        homeHeroEyebrow: fields.text({ label: 'Home hero eyebrow' }),
        homeStat1Label: fields.text({ label: 'Home stat 1 label' }),
        homeStat1Sub: fields.text({ label: 'Home stat 1 sublabel' }),
        homeStat2Label: fields.text({ label: 'Home stat 2 label' }),
        homeStat2Sub: fields.text({ label: 'Home stat 2 sublabel' }),
        homeStat3Label: fields.text({ label: 'Home stat 3 label' }),
        homeStat3Sub: fields.text({ label: 'Home stat 3 sublabel' }),
        homeHeroFallbackKicker: fields.text({ label: 'Home hero fallback kicker' }),
        homeHeroFallbackTitle: fields.text({ label: 'Home hero fallback title' }),
        homeHeroFallbackBody: fields.text({ label: 'Home hero fallback body', multiline: true }),
        homeAccountabilityTitle: fields.text({ label: 'Home accountability title' }),
        homeAccountabilityBody: fields.text({ label: 'Home accountability body', multiline: true }),
        homeTrustStrip: fields.array(fields.text({ label: 'Trust item' }), { label: 'Home trust strip items' }),
        homeApproachEyebrow: fields.text({ label: 'Home approach eyebrow' }),
        homeOutcomesEyebrow: fields.text({ label: 'Home outcomes eyebrow' }),
        homeMissionEyebrow: fields.text({ label: 'Home mission eyebrow' }),
        homeFocusEyebrow: fields.text({ label: 'Home focus areas eyebrow' }),
        homePillarCta: fields.text({ label: 'Home pillar card CTA' }),
        homeEvidenceEyebrow: fields.text({ label: 'Home evidence eyebrow' }),
        homeEvidenceTitle: fields.text({ label: 'Home evidence title' }),
        homeEvidenceIntro: fields.text({ label: 'Home evidence intro', multiline: true }),
        homeImpactLearnersLabel: fields.text({ label: 'Home impact learners label' }),
        homeImpactLearnersBody: fields.text({ label: 'Home impact learners body', multiline: true }),
        homeImpactVolunteersLabel: fields.text({ label: 'Home impact volunteers label' }),
        homeImpactVolunteersBody: fields.text({ label: 'Home impact volunteers body', multiline: true }),
        homeImpactCampaignsLabel: fields.text({ label: 'Home impact campaigns label' }),
        homeImpactCampaignsBody: fields.text({ label: 'Home impact campaigns body', multiline: true }),
        homeImpactEmploymentLabel: fields.text({ label: 'Home impact employment label' }),
        homeImpactEmploymentBody: fields.text({ label: 'Home impact employment body', multiline: true }),
        homePartnershipsEyebrow: fields.text({ label: 'Home partnerships eyebrow' }),
        homeProgramsEyebrow: fields.text({ label: 'Home programs eyebrow' }),
        homeProgramsTitle: fields.text({ label: 'Home programs title' }),
        homeProgramsIntro: fields.text({ label: 'Home programs intro', multiline: true }),
        homeProgramsAllLabel: fields.text({ label: 'Home programs all button label' }),
        homeProgramsCardCta: fields.text({ label: 'Home programs card CTA' }),
        homeEmpowermentEyebrow: fields.text({ label: 'Home empowerment eyebrow' }),
        homeEmpowermentTitle: fields.text({ label: 'Home empowerment title' }),
        homeVoicesEyebrow: fields.text({ label: 'Home voices eyebrow' }),
        homeVoicesTitle: fields.text({ label: 'Home voices title' }),
        homeQuestionsEyebrow: fields.text({ label: 'Home questions eyebrow' }),
        homeQuestionsTitle: fields.text({ label: 'Home questions title' }),
        homeUpdatesEyebrow: fields.text({ label: 'Home updates eyebrow' }),
        homeUpdatesTitle: fields.text({ label: 'Home updates title' }),
        homeUpdatesAllLabel: fields.text({ label: 'Home updates all label' }),
        homeGovernanceEyebrow: fields.text({ label: 'Home governance eyebrow' }),
        homeGovernanceTitle: fields.text({ label: 'Home governance title' }),
        homeGovernanceIntro: fields.text({ label: 'Home governance intro', multiline: true }),
        homeComplianceLabel: fields.text({ label: 'Home compliance label' }),
        homeComplianceTitle: fields.text({ label: 'Home compliance title' }),
        homeComplianceBody: fields.text({ label: 'Home compliance body', multiline: true }),
        homeSafeguardingLabel: fields.text({ label: 'Home safeguarding label' }),
        homeSafeguardingTitle: fields.text({ label: 'Home safeguarding title' }),
        homeSafeguardingBody: fields.text({ label: 'Home safeguarding body', multiline: true }),
        homeWorkflowLabel: fields.text({ label: 'Home workflow label' }),
        homeWorkflowStep1: fields.text({ label: 'Home workflow step 1', multiline: true }),
        homeWorkflowStep2: fields.text({ label: 'Home workflow step 2', multiline: true }),
        homeWorkflowStep3: fields.text({ label: 'Home workflow step 3', multiline: true }),
        homeFinalEyebrow: fields.text({ label: 'Home final CTA eyebrow' }),
        homeFinalPrimaryLabel: fields.text({ label: 'Home final CTA primary button label' }),
        homeFinalVolunteerLabel: fields.text({ label: 'Home final CTA volunteer button label' }),
        homeFinalCallLabel: fields.text({ label: 'Home final CTA call prefix' }),

        aboutPageEyebrow: fields.text({ label: 'About page eyebrow' }),
        aboutPageTitle: fields.text({ label: 'About page title' }),
        aboutPageIntro: fields.text({ label: 'About page intro', multiline: true }),
        aboutSidebarEyebrow: fields.text({ label: 'About sidebar eyebrow' }),
        aboutSidebarTitle: fields.text({ label: 'About sidebar title' }),
        aboutSidebarBody: fields.text({ label: 'About sidebar body', multiline: true }),
        aboutSidebarCtaLabel: fields.text({ label: 'About sidebar CTA label' }),
        aboutStandardsEyebrow1: fields.text({ label: 'About standards card 1 eyebrow' }),
        aboutStandardsTitle1: fields.text({ label: 'About standards card 1 title' }),
        aboutStandardsBody1: fields.text({ label: 'About standards card 1 body', multiline: true }),
        aboutStandardsEyebrow2: fields.text({ label: 'About standards card 2 eyebrow' }),
        aboutStandardsTitle2: fields.text({ label: 'About standards card 2 title' }),
        aboutStandardsBody2: fields.text({ label: 'About standards card 2 body', multiline: true }),
        aboutStandardsEyebrow3: fields.text({ label: 'About standards card 3 eyebrow' }),
        aboutStandardsTitle3: fields.text({ label: 'About standards card 3 title' }),
        aboutStandardsBody3: fields.text({ label: 'About standards card 3 body', multiline: true }),
        aboutGovernanceEyebrow: fields.text({ label: 'About governance eyebrow' }),
        aboutTeamTitle: fields.text({ label: 'About team section title' }),
        aboutTeamIntro: fields.text({ label: 'About team intro', multiline: true }),

        contactPageEyebrow: fields.text({ label: 'Contact page eyebrow' }),
        contactPageTitle: fields.text({ label: 'Contact page title' }),
        contactPartnershipTitle: fields.text({ label: 'Contact partnership card title' }),
        contactPartnershipBody: fields.text({ label: 'Contact partnership body', multiline: true }),
        contactPartnershipBullet1: fields.text({ label: 'Contact partnership bullet 1' }),
        contactPartnershipBullet2: fields.text({ label: 'Contact partnership bullet 2' }),
        contactPartnershipBullet3: fields.text({ label: 'Contact partnership bullet 3' }),
        contactPartnershipButtonLabel: fields.text({ label: 'Contact partnership button label' }),

        pillars: fields.array(
          fields.object({
            title: fields.text({ label: 'Title' }),
            body: fields.text({ label: 'Description', multiline: true }),
          }),
          { label: 'Home: program pillars (4 cards)' }
        ),
        empowermentBlocks: fields.array(
          fields.object({
            kicker: fields.text({ label: 'Small label' }),
            title: fields.text({ label: 'Title' }),
            body: fields.text({ label: 'Body', multiline: true }),
          }),
          { label: 'Home: empowerment cards' }
        ),
        faqs: fields.array(
          fields.object({
            question: fields.text({ label: 'Question' }),
            answer: fields.text({ label: 'Answer', multiline: true }),
          }),
          { label: 'FAQs' }
        ),
      },
    }),
  },
  collections: {
    programs: collection({
      label: 'Programs',
      slugField: 'slug',
      path: 'content/programs/*',
      format: { data: 'json' },
      schema: {
        title: fields.text({ label: 'Title' }),
        slug: fields.slug({ name: { label: 'URL slug' } }),
        summary: fields.text({ label: 'Short summary', multiline: true }),
        coverImage: fields.image({
          label: 'Cover image',
          ...programImages,
          validation: { isRequired: true },
        }),
        coverImageAlt: fields.text({
          label: 'Cover image alt text',
          validation: { isRequired: false },
        }),
        gallery: fields.array(
          fields.object({
            image: fields.image({ label: 'Photo', ...programImages }),
            alt: fields.text({ label: 'Photo alt text', validation: { isRequired: false } }),
          }),
          { label: 'Photo gallery' }
        ),
        bodyMarkdown: fields.text({
          label: 'Full description (Markdown)',
          multiline: true,
          description: 'Use headings, lists, and **bold**. Images: ![alt](/site/programs/your-file.jpg)',
        }),
        order: fields.integer({ label: 'Sort order (lower first)' }),
        featuredOnHome: fields.checkbox({
          label: 'Show on homepage strip',
          defaultValue: true,
        }),
      },
    }),
    posts: collection({
      label: 'Blog posts',
      slugField: 'slug',
      path: 'content/posts/*',
      format: { data: 'json' },
      schema: {
        title: fields.text({ label: 'Title' }),
        slug: fields.slug({ name: { label: 'URL slug' } }),
        publishDate: fields.date({ label: 'Publish date' }),
        excerpt: fields.text({ label: 'Excerpt', multiline: true }),
        coverImage: fields.image({
          label: 'Cover image',
          ...blogImages,
          validation: { isRequired: true },
        }),
        coverImageAlt: fields.text({
          label: 'Cover image alt text',
          validation: { isRequired: false },
        }),
        bodyMarkdown: fields.text({
          label: 'Post body (Markdown)',
          multiline: true,
        }),
      },
    }),
    testimonials: collection({
      label: 'Testimonials',
      slugField: 'slug',
      path: 'content/testimonials/*',
      format: { data: 'json' },
      schema: {
        name: fields.text({ label: 'Name' }),
        slug: fields.slug({ name: { label: 'URL slug' } }),
        role: fields.text({ label: 'Role / context (e.g. employer)' }),
        quote: fields.text({ label: 'Quote', multiline: true }),
        photo: fields.image({
          label: 'Photo (optional)',
          directory: 'public/site/testimonials',
          publicPath: '/site/testimonials/',
        }),
        photoAlt: fields.text({
          label: 'Photo alt text',
          validation: { isRequired: false },
        }),
        order: fields.integer({ label: 'Sort order' }),
      },
    }),
    team: collection({
      label: 'Team',
      slugField: 'slug',
      path: 'content/team/*',
      format: { data: 'json' },
      schema: {
        name: fields.text({ label: 'Name' }),
        slug: fields.slug({ name: { label: 'URL slug' } }),
        role: fields.text({ label: 'Role' }),
        photo: fields.image({
          label: 'Photo',
          directory: 'public/site/team',
          publicPath: '/site/team/',
        }),
        photoAlt: fields.text({
          label: 'Photo alt text',
          validation: { isRequired: false },
        }),
        order: fields.integer({ label: 'Sort order' }),
      },
    }),
  },
});
